// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwNVCYpv03IokfuBeEoABhnNi0qX2bm4w',
    appId: '1:435582516067:web:22c1a586e47538acf7b156',
    messagingSenderId: '435582516067',
    projectId: 'household-budget-b003a',
    authDomain: 'household-budget-b003a.firebaseapp.com',
    storageBucket: 'household-budget-b003a.firebasestorage.app',
    measurementId: 'G-9HEBQL8Z60',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwvLhMf2-ybHEXm0TYBCgOnWcnn_nxyGA',
    appId: '1:435582516067:android:93ff28d6aa2fa1e8f7b156',
    messagingSenderId: '435582516067',
    projectId: 'household-budget-b003a',
    storageBucket: 'household-budget-b003a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnq00FdlfNvdHiY2GSnA9Hlc7oMucxCm0',
    appId: '1:435582516067:ios:65eb8b796ee4f47df7b156',
    messagingSenderId: '435582516067',
    projectId: 'household-budget-b003a',
    storageBucket: 'household-budget-b003a.firebasestorage.app',
    iosBundleId: 'com.example.householdBudget',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnq00FdlfNvdHiY2GSnA9Hlc7oMucxCm0',
    appId: '1:435582516067:ios:65eb8b796ee4f47df7b156',
    messagingSenderId: '435582516067',
    projectId: 'household-budget-b003a',
    storageBucket: 'household-budget-b003a.firebasestorage.app',
    iosBundleId: 'com.example.householdBudget',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwNVCYpv03IokfuBeEoABhnNi0qX2bm4w',
    appId: '1:435582516067:web:4276d9d0d77a59b6f7b156',
    messagingSenderId: '435582516067',
    projectId: 'household-budget-b003a',
    authDomain: 'household-budget-b003a.firebaseapp.com',
    storageBucket: 'household-budget-b003a.firebasestorage.app',
    measurementId: 'G-LDM4ZVKCQZ',
  );
}
